### ISSUE TITLE
[FR] Annoncement ne fonctionnent plus

### ISSUE THREAD

**Issue by Zino2201** [UpGunGame/UpGun-Issues#143]

**Comment by MaxEstDev** [comment]
![image](https://user-images.githubusercontent.com/96690800/163444781-d8c2ff33-75ca-4315-81d8-fc460ec8ec8a.png)
à mon avis c'est parce que les dégâts des balles, par défaut c'est "DamageType.Bullet" et je peux pas le mettre dans le score

**Comment by MaxEstDev** [comment]
Soit on fait un dégât "défaut" soit faut voir un autre truc jsp
