### ISSUE TITLE
[FR] Crash en fin de game

### ISSUE THREAD

**Issue by MaxEstDev** [UpGunGame/UpGun-Issues#152]
Assertion failed: O != 0 [File:C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Intermediate\Build\Win64\UE4\Inc\UpGun\UpGunDamageableInterface.gen.cpp] [Line: 145]

UpGun_Win64_DebugGame!FDebug::AssertFailed()
UpGun_Win64_DebugGame!FDebug::CheckVerifyFailedImpl()
UpGun_Win64_DebugGame!`IUpGunDamageableInterface::Execute_Damage'::`6'::Impl::ExecCheckImplInternal() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Intermediate\Build\Win64\UE4\Inc\UpGun\UpGunDamageableInterface.gen.cpp:145]
UpGun_Win64_DebugGame!IUpGunDamageableInterface::Execute_Damage() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Intermediate\Build\Win64\UE4\Inc\UpGun\UpGunDamageableInterface.gen.cpp:145]
UpGun_Win64_DebugGame!UUpGunDamageAttributeSet::PostGameplayEffectExecute() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Source\UpGun\Damage\UpGunDamageAttributeSet.cpp:94]
UpGun_Win64_DebugGame!UUpGunBaseCharacterAttributeSet::PostGameplayEffectExecute() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Source\UpGun\Character\UpGunBaseCharacterAttributeSet.cpp:127]
UpGun_Win64_DebugGame!FActiveGameplayEffectsContainer::InternalExecuteMod()
UpGun_Win64_DebugGame!FActiveGameplayEffectsContainer::ExecuteActiveEffectsFrom()
UpGun_Win64_DebugGame!FActiveGameplayEffectsContainer::InternalExecutePeriodicGameplayEffect()
UpGun_Win64_DebugGame!FActiveGameplayEffectsContainer::ExecutePeriodicGameplayEffect()
UpGun_Win64_DebugGame!FTimerUnifiedDelegate::Execute()
UpGun_Win64_DebugGame!FTimerManager::Tick()
UpGun_Win64_DebugGame!UWorld::Tick()
UpGun_Win64_DebugGame!UGameEngine::Tick()
UpGun_Win64_DebugGame!FEngineLoop::Tick()
UpGun_Win64_DebugGame!GuardedMain()
UpGun_Win64_DebugGame!GuardedMainWrapper()
UpGun_Win64_DebugGame!WinMain()
UpGun_Win64_DebugGame!__scrt_common_main_seh() [d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by Zino2201** [comment]
Second crash

Assertion failed: O->GetClass()->ImplementsInterface(UUpGunDamageableInterface::StaticClass()) [File:C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Intermediate\Build\Win64\UE4\Inc\UpGun\UpGunDamageableInterface.gen.cpp] [Line: 146]

UpGun_Win64_DebugGame!FDebug::AssertFailed()
UpGun_Win64_DebugGame!FDebug::CheckVerifyFailedImpl()
UpGun_Win64_DebugGame!`IUpGunDamageableInterface::Execute_Damage'::`10'::Impl::ExecCheckImplInternal() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Intermediate\Build\Win64\UE4\Inc\UpGun\UpGunDamageableInterface.gen.cpp:146]
UpGun_Win64_DebugGame!IUpGunDamageableInterface::Execute_Damage() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Intermediate\Build\Win64\UE4\Inc\UpGun\UpGunDamageableInterface.gen.cpp:146]
UpGun_Win64_DebugGame!UUpGunDamageAttributeSet::PostGameplayEffectExecute() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Source\UpGun\Damage\UpGunDamageAttributeSet.cpp:94]
UpGun_Win64_DebugGame!UUpGunBaseCharacterAttributeSet::PostGameplayEffectExecute() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Source\UpGun\Character\UpGunBaseCharacterAttributeSet.cpp:127]
UpGun_Win64_DebugGame!FActiveGameplayEffectsContainer::InternalExecuteMod()
UpGun_Win64_DebugGame!FActiveGameplayEffectsContainer::ExecuteActiveEffectsFrom()
UpGun_Win64_DebugGame!UAbilitySystemComponent::ExecuteGameplayEffect()
UpGun_Win64_DebugGame!UAbilitySystemComponent::ApplyGameplayEffectSpecToSelf()
UpGun_Win64_DebugGame!UUpGunDamageStatics::ApplyRadialDamage() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Source\UpGun\Damage\UpGunDamageStatics.cpp:189]
UpGun_Win64_DebugGame!UUpGunDamageStatics::execApplyRadialDamage() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Intermediate\Build\Win64\UE4\Inc\UpGun\UpGunDamageStatics.gen.cpp:62]
UpGun_Win64_DebugGame!UObject::execCallMathFunction()
UpGun_Win64_DebugGame!ProcessLocalScriptFunction()

**Comment by MaxEstDev** [comment]
Visiblement le crash est toujours là 
LoginId:07fc83f244d3395b26dd07b3b45adf0e
EpicAccountId:389c443089664b5d98e932985f968d92

Assertion failed: IsInGameThread() || IsInSlateThread() [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/SlateCore/Private/Widgets/SWidget.cpp] [Line: 1119] Slate can only be accessed from the GameThread or the SlateLoadingThread!

UpGun_Win64_DebugGame!FDebug::AssertFailed()
UpGun_Win64_DebugGame!FDebug::CheckVerifyFailedImpl()
UpGun_Win64_DebugGame!SWidget::Invalidate()
UpGun_Win64_DebugGame!SBorder::SetPadding()
UpGun_Win64_DebugGame!UBorderSlot::BuildSlot()
UpGun_Win64_DebugGame!UBorder::RebuildWidget()
UpGun_Win64_DebugGame!UWidget::TakeWidget_Private()
UpGun_Win64_DebugGame!UUserWidget::RebuildWidget()
UpGun_Win64_DebugGame!UWidget::TakeWidget_Private()
UpGun_Win64_DebugGame!UOverlaySlot::BuildSlot()
UpGun_Win64_DebugGame!UOverlay::OnSlotAdded()
UpGun_Win64_DebugGame!UPanelWidget::AddChild()
UpGun_Win64_DebugGame!UOverlay::AddChildToOverlay()
UpGun_Win64_DebugGame!UOverlay::execAddChildToOverlay()
UpGun_Win64_DebugGame!UFunction::Invoke()
UpGun_Win64_DebugGame!UObject::CallFunction()
UpGun_Win64_DebugGame!UObject::ProcessContextOpcode()
UpGun_Win64_DebugGame!UObject::execLetObj()
UpGun_Win64_DebugGame!ProcessLocalScriptFunction()
UpGun_Win64_DebugGame!ProcessScriptFunction<void (__cdecl*)(UObject * __ptr64,FFrame & __ptr64,void * __ptr64)>()
UpGun_Win64_DebugGame!ProcessLocalFunction()
UpGun_Win64_DebugGame!ProcessLocalScriptFunction()
UpGun_Win64_DebugGame!UObject::ProcessInternal()
UpGun_Win64_DebugGame!UFunction::Invoke()
UpGun_Win64_DebugGame!UObject::ProcessEvent()
UpGun_Win64_DebugGame!TMulticastScriptDelegate<FWeakObjectPtr>::ProcessMulticastDelegate<UObject>()
UpGun_Win64_DebugGame!FUpGunInventorySubsystemOnItemDropped_DelegateWrapper() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Source\UpGun\OSS\UpGunInventorySubsystem.h:182]
UpGun_Win64_DebugGame!TWeakBaseFunctorDelegateInstance<UUpGunInventorySubsystem,void __cdecl(FUpGunInventoryItem const &),FDefaultDelegateUserPolicy,<lambda_29e5c5158f4b81593a5fcfdcd93c17ea> >::ExecuteIfSafe() [G:\UE_4.26\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:955]
UpGun_Win64_DebugGame!TMulticastDelegate<void __cdecl(FUpGunInventoryItem const &),FDefaultDelegateUserPolicy>::Broadcast() [G:\UE_4.26\Engine\Source\Runtime\Core\Public\Delegates\DelegateSignatureImpl.inl:955]
UpGun_Win64_DebugGame!FUpGunSteamInventoryService::OnInventoryResultReady_OSSThread() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Source\UpGun\OSS\Steam\UpGunSteamInventoryService.cpp:70]
UpGun_Win64_DebugGame!FUpGunSteamInventoryService::CCallbackInternal_OnInventoryResultReady_OSSThread::Run() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Source\UpGun\OSS\Steam\UpGunSteamInventoryService.h:19]
steam_api64
steam_api64
steam_api64
steam_api64
steam_api64
UpGun_Win64_DebugGame!FOnlineAsyncTaskManagerSteamUpGun::OnlineTick() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Plugins\OnlineSubsystemSteamUpGun\Source\Private\OnlineAsyncTaskManagerSteamUpGun.cpp:27]
UpGun_Win64_DebugGame!FOnlineAsyncTaskManager::Tick()
UpGun_Win64_DebugGame!FOnlineAsyncTaskManager::Run()
UpGun_Win64_DebugGame!FRunnableThreadWin::Run()

**Comment by MaxEstDev** [comment]
je crois pas que ça soit bon ça
