### ISSUE TITLE
[FR] SLAM ne marche pas

### ISSUE THREAD

**Issue by Zino2201** [UpGunGame/UpGun-Issues#164]

**Comment by MaxEstDev** [comment]
ça fonctionne coté serveur
+ j'ai mis les bonnes couleurs pour les particules

**Comment by Zino2201** [comment]
Le soucis vient de la synchro client-serveur, surtout avec beaucoup de ping. Le seul moyen de régler ça proprement sans désavantagé trop le client pour le moment c'est de ne pas prédire l'abilité.
