### ISSUE TITLE
mon jeu crash quand je join une game[FR]

### ISSUE THREAD

**Issue by FoxyTheVixen** [UpGunGame/UpGun-Issues#208]
Mon jeu crash quand je join une game, j'ai essayer plusieurs fois et a chaque fois c'est le cas

je lance mon jeu
je fais dans la liste de parties ouverte
je join, ca me montre la map puis je crash

bah je ne devrais pas crash :(

![oscour](https://user-images.githubusercontent.com/35465089/168435145-5b38120e-e96e-40dc-9db0-ecddf538cd98.png)

**Comment by weuve77** [comment]
Même souci pour moi :)

**Comment by FoxyTheVixen** [comment]
LoginId:a3fe79994fd951e7b835769689feeec4
EpicAccountId:be93174bf53042428a85a5a763397660

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000370

UpGun_Win64_Shipping!AUpGunDeathmatchPlayerState::IsInTheSameTeam() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Source\UpGun\Deathmatch\UpGunDeathmatchPlayerState.cpp:59]
UpGun_Win64_Shipping!AUpGunBasePlayerState::execIsInTheSameTeam() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Intermediate\Build\Win64\UE4\Inc\UpGun\UpGunBasePlayerState.gen.cpp:508]
UpGun_Win64_Shipping!UFunction::Invoke()
UpGun_Win64_Shipping!UObject::CallFunction()
UpGun_Win64_Shipping!UObject::ProcessContextOpcode()
UpGun_Win64_Shipping!UObject::execLetBool()
UpGun_Win64_Shipping!ProcessLocalScriptFunction()
UpGun_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject * __ptr64,FFrame & __ptr64,void * __ptr64)>()
UpGun_Win64_Shipping!UObject::execLocalFinalFunction()
UpGun_Win64_Shipping!ProcessLocalScriptFunction()
UpGun_Win64_Shipping!UObject::ProcessInternal()
UpGun_Win64_Shipping!UFunction::Invoke()
UpGun_Win64_Shipping!UObject::ProcessEvent()
UpGun_Win64_Shipping!UUserWidget::Tick()
UpGun_Win64_Shipping!UUserWidget::NativeTick()
UpGun_Win64_Shipping!SObjectWidget::Tick()
UpGun_Win64_Shipping!SWidget::Paint()
UpGun_Win64_Shipping!SBox::OnPaint()
UpGun_Win64_Shipping!SWidget::Paint()
UpGun_Win64_Shipping!SConstraintCanvas::OnPaint()
UpGun_Win64_Shipping!SWidget::Paint()
UpGun_Win64_Shipping!SCompoundWidget::OnPaint()
UpGun_Win64_Shipping!SWidget::Paint()
UpGun_Win64_Shipping!SOverlay::OnPaint()
UpGun_Win64_Shipping!SPlayerLayer::OnPaint()
UpGun_Win64_Shipping!SWidget::Paint()
UpGun_Win64_Shipping!SCanvas::OnPaint()
UpGun_Win64_Shipping!SWidget::Paint()
UpGun_Win64_Shipping!SOverlay::OnPaint()
UpGun_Win64_Shipping!SWidget::Paint()
UpGun_Win64_Shipping!SPanel::PaintArrangedChildren()
UpGun_Win64_Shipping!SPanel::OnPaint()
UpGun_Win64_Shipping!SWidget::Paint()
UpGun_Win64_Shipping!SPanel::PaintArrangedChildren()
UpGun_Win64_Shipping!SPanel::OnPaint()
UpGun_Win64_Shipping!SWidget::Paint()
UpGun_Win64_Shipping!SCompoundWidget::OnPaint()
UpGun_Win64_Shipping!SWidget::Paint()
UpGun_Win64_Shipping!SCompoundWidget::OnPaint()
UpGun_Win64_Shipping!SViewport::OnPaint()
UpGun_Win64_Shipping!SWidget::Paint()
UpGun_Win64_Shipping!SPanel::PaintArrangedChildren()
UpGun_Win64_Shipping!SPanel::OnPaint()
UpGun_Win64_Shipping!SWidget::Paint()
UpGun_Win64_Shipping!SOverlay::OnPaint()
UpGun_Win64_Shipping!SWidget::Paint()
UpGun_Win64_Shipping!SCompoundWidget::OnPaint()
UpGun_Win64_Shipping!SWidget::Paint()
UpGun_Win64_Shipping!SWindow::PaintSlowPath()
UpGun_Win64_Shipping!FSlateInvalidationRoot::PaintInvalidationRoot()
UpGun_Win64_Shipping!SWindow::PaintWindow()
UpGun_Win64_Shipping!FSlateApplication::DrawWindowAndChildren()
UpGun_Win64_Shipping!FSlateApplication::PrivateDrawWindows()
UpGun_Win64_Shipping!FSlateApplication::TickAndDrawWidgets()
UpGun_Win64_Shipping!FSlateApplication::Tick()
UpGun_Win64_Shipping!FEngineLoop::Tick()
UpGun_Win64_Shipping!GuardedMain()
UpGun_Win64_Shipping!GuardedMainWrapper()
UpGun_Win64_Shipping!WinMain()
UpGun_Win64_Shipping!__scrt_common_main_seh() [d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll


le crash report parce que je suis pas sur que le screen aide

**Comment by Gbasire** [comment]
Même soucis pour moi, avec de très bons composants dans mon PC (RTX 3060, i7 11800H, 16go RAM)

Mon crash report : 

LoginId:30fd6fbb4f8c6d0d2322a78af067bd47
EpicAccountId:7a38b8d0cc1d4f3983e011fc7233a2c2

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000288

UpGun_Win64_Shipping!AUpGunDeathmatchGhost::OnCosmeticSettingsUpdated() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Source\UpGun\Deathmatch\UpGunDeathmatchGhost.cpp:226]
UpGun_Win64_Shipping!AUpGunDeathmatchGhost::OnRep_PlayerState() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Source\UpGun\Deathmatch\UpGunDeathmatchGhost.cpp:138]
UpGun_Win64_Shipping!UFunction::Invoke()
UpGun_Win64_Shipping!UObject::ProcessEvent()
UpGun_Win64_Shipping!AActor::ProcessEvent()
UpGun_Win64_Shipping!FRepLayout::CallRepNotifies()
UpGun_Win64_Shipping!FObjectReplicator::CallRepNotifies()
UpGun_Win64_Shipping!FObjectReplicator::UpdateUnmappedObjects()
UpGun_Win64_Shipping!UNetDriver::TickFlush()
UpGun_Win64_Shipping!TBaseUObjectMethodDelegateInstance<0,ADefaultPawn,void __cdecl(float),FDefaultDelegateUserPolicy>::ExecuteIfSafe()
UpGun_Win64_Shipping!TMulticastDelegate<void __cdecl(float),FDefaultDelegateUserPolicy>::Broadcast()
UpGun_Win64_Shipping!UWorld::Tick()
UpGun_Win64_Shipping!UGameEngine::Tick()
UpGun_Win64_Shipping!FEngineLoop::Tick()
UpGun_Win64_Shipping!GuardedMain()
UpGun_Win64_Shipping!GuardedMainWrapper()
UpGun_Win64_Shipping!WinMain()
UpGun_Win64_Shipping!__scrt_common_main_seh() [d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by Zino2201** [comment]
merci les gars, je vais voir tout ça!

**Comment by remixardin** [comment]
mon jeux crash quand je veux rejoindre que certain partie pas tout

**Comment by Meca-3D** [comment]
j'ai l'impression que mon jeux crash seulement sur la nouvel map (je ne suis pas sur)

**Comment by FoxyTheVixen** [comment]
perso je n'ai plus de crash avec le nouveau patch, merci je peux enfin jouer au jeu video B^)
