### ISSUE TITLE
mixeur de volume[FR]

### ISSUE THREAD

**Issue by Yuna-sudo** [UpGunGame/UpGun-Issues#209]
**Décrivez le bug**
Le logo du jeu ne s'affiche pas dans le mélangeur de son

**Pour reproduire le bug**
Etapes pour reproduire le bug:
1. clique droit sur le logo son
2. Cliquer sur : Ouvrir le mélangeur de volume
3. Trouver le jeu dans le mélangeur de volume

**Comment by MaxEstDev** [comment]
Yes le logo est pas encore remis

**Comment by Zino2201** [comment]
voir #228
