### ISSUE TITLE
[FR] Petit bug avec le podium des ''gagnants''

### ISSUE THREAD

**Issue by OniKirby** [UpGunGame/UpGun-Issues#213]
Je ne sais pas comment le reproduire mais petit bug sur le podium je suis 3e mais je suis situer a la 2e position.
![20220514113255_1](https://user-images.githubusercontent.com/105556234/168438503-74e15f19-1033-4324-8d63-3f35a6711056.jpg)

**Comment by MaxEstDev** [comment]
C'est corrigé ! Merci bien !
