### ISSUE TITLE
[FR] L'amélioration viseur ne fonctionne pas

### ISSUE THREAD

**Issue by Gbasire** [UpGunGame/UpGun-Issues#217]
**Décrivez le bug**
Lorse que l'on tente d'utiliser le viseur, un début d'animation de viseur se lance avant de revenir directement à la normale, même si a touche est pressée longuement

**Pour reproduire le bug**
Etapes pour reproduire le bug:
1. Avoir l'amélioration Viseur
2. Utiliser sa touche de Viseur

**Comportement attendu**
Le personnage entre dans une nouvelle pose pour tirer plus précisément

**Comment by MaxEstDev** [comment]
Je ne parviens pas à reproduire le bug, tu penses pouvoir le filmer ?

**Comment by Gbasire** [comment]
Si j'arrive à le reproduire oui aucun soucis
