### ISSUE TITLE
[FR] Conteneur en lévitation

### ISSUE THREAD

**Issue by Matuvu16-16** [UpGunGame/UpGun-Issues#226]
Sur la map Platforme pétrolière, le conteneur est en lévitation.

**Screenshots**
![image_2022-05-14_203158767](https://user-images.githubusercontent.com/67476124/168444179-8685003f-9865-4654-acc2-bb2280f3025f.png)

**Comment by MaxEstDev** [comment]
oui c'est pas le modèle definitif pour la cable :)

**Comment by MaxEstDev** [comment]
![image](https://user-images.githubusercontent.com/96690800/168491555-11b9962e-78af-4a2d-bbd2-39d3b80fb899.png)
C'est bon !
