### ISSUE TITLE
[FR] Grappin sur les skybox

### ISSUE THREAD

**Issue by AlexE7Pilou** [UpGunGame/UpGun-Issues#233]
**Décrivez le bug**
On peux grappiner sur la skybox dans ferme.

**Pour reproduire le bug**
Etapes pour reproduire le bug:
1. Viser le ciel ou les murs
2. Grapinnez

Vidéo
https://cdn.discordapp.com/attachments/925683214272569394/975137156123218010/2022-05-14_22-45-14.mp4
_Enfaite on vois rien sur la vidéo, ça a commencé a record après le grappin, ça sert a rien. Mais on peux_

**Comment by MaxEstDev** [comment]
On est bon ici !
