### ISSUE TITLE
[FR] Améliorations par défaut pas sélectionnables

### ISSUE THREAD

**Issue by UnePouleSDF** [UpGunGame/UpGun-Issues#234]
Les améliorations par défaut ne sont pas sélectionnables , je ne pense pas en avoir à ajouter vu que c'est constant

**Comment by MaxEstDev** [comment]
Slt !
T'as un screen de ce dont tu parles ?

**Comment by UnePouleSDF** [comment]
Je peux pas faire plus explicatif que cette vidéo, j'essaie de cliquer ça veut pas mettre d'améliorations de base et c'est tout le temps comme ça

https://user-images.githubusercontent.com/105566210/168472876-b0b59af0-5a9f-4927-b61b-74783853e5ca.mp4

**Comment by MaxEstDev** [comment]
Euh c'est pas un bug il faut cliquer sur les barres à droite pour choisir le niveau

**Comment by MaxEstDev** [comment]
J'ai quand même pris le temps de modifier le système pour que cliquer donne également un niveau
