### ISSUE TITLE
[FR] IK personnage buggé au spawn

### ISSUE THREAD

**Issue by Zino2201** [UpGunGame/UpGun-Issues#240]
**Décrivez le bug**
L'IK des jambes du perso est buggé au spawn, dés qu'on se déplace c'est good.

**Comportement attendu**
Une pose normale.

**Comment by MaxEstDev** [comment]
J'ai changé un peu de code, à voir

**Comment by MaxEstDev** [comment]
Je vais changer encore plus de code dessus soon

**Comment by MaxEstDev** [comment]
C'est bon !
