### ISSUE TITLE
[FR] Bug plateforme pétrolière clipping sol

### ISSUE THREAD

**Issue by UnePouleSDF** [UpGunGame/UpGun-Issues#241]
**Décrivez le bug**
clipping en dessous de la plateforme, on peut tirer à travers et les ennemis nous voient pas

**Pour reproduire le bug**
-Montez sur des cageots tout en bas de la plateforme en vous accroupissant
-S'il y a un autre obstacle plus haut avancez vers lui
-Normalement votre caméra devrait clipper à travers le sol de l'étage supérieur et vous pourrez tirer

**Screenshots**

https://user-images.githubusercontent.com/105566210/168449990-9adad12a-e143-4619-8dc9-85b664a1d97c.mp4

**Comment by MaxEstDev** [comment]
C'est bon !
