### ISSUE TITLE
[FR] Plateforme pétrolière les murs invisibles

### ISSUE THREAD

**Issue by UnePouleSDF** [UpGunGame/UpGun-Issues#242]
**Décrivez le bug**
les murs invisibles de la plateforme pétrolière ne sont pas assez haut (on peut juste les retirer pour donner plus de hauteur au jeu)

**Pour reproduire le bug**
Matériel nécessaire : grappin
Facultatif : disque de tp (mais c'est plus facile)
-Viser le haut du mur invisible de la vidéo en bas
-C'est tout

**Screenshots**

https://user-images.githubusercontent.com/105566210/168450052-eaceb46f-87fa-41c9-a126-ad7b7e04f815.mp4

**Comment by Zino2201** [comment]
voir #233
