### ISSUE TITLE
[FR] Partie privée

### ISSUE THREAD

**Issue by UnePouleSDF** [UpGunGame/UpGun-Issues#243]
Même en partie privé des personnes peuvent rejoindre

**Comment by Zino2201** [comment]
il faut plus de précision, la personne t'a rejoint avec une invitation/un code ?

**Comment by UnePouleSDF** [comment]
non j'étais afk seul round 7 pour report un bug et quand je suis revenu je voyais 2 drone se faisant la course, j'ai fait tab et c'etait des joueurs

**Comment by Zino2201** [comment]
Hum, je soupçonne que ça soit lié au code qui sont buggé dans ce patch, et y'a des collisions. On verra au prochain patch. Pour le moment je close.
