### ISSUE TITLE
[FR] On garde les capacités qu'on a mis par défault

### ISSUE THREAD

**Issue by OniKirby** [UpGunGame/UpGun-Issues#246]
En gros toute les capacités que j'ai mis par défauts lors de ma partie précédent sont conserver une fois de retour dans le Lobby
![20220514191733_1](https://user-images.githubusercontent.com/105556234/168451062-c8e422b8-584e-4915-a279-962b378ad8d2.jpg)

**Comment by OniKirby** [comment]
C'était déjà signaler?

**Comment by Zino2201** [comment]
Ouais, on avait fix du coup :)

**Comment by OniKirby** [comment]
Mais pourtant je suis bien a jour ?

**Comment by Zino2201** [comment]
Ah c'est pour le prochain patch déso j'ai oublié de précisé
