### ISSUE TITLE
[FR] Bug "OOB" everstopped

### ISSUE THREAD

**Issue by enzomtpYT** [UpGunGame/UpGun-Issues#249]
**Décrivez le bug**
Un bug permettant d'oob sur des cartons sur la map everstopped

**Pour reproduire le bug**
Etapes pour reproduire le bug:
1. Allez dans la salle a cartons
2. Sauter sur le premier carton
3. Sauter sur les autres cartons en shiftant
4. Placez vous sur le carton carré un peu plus au que les autres
5. Vous voila avec la possibilité de tirer a travers les murs !

**Comportement attendu**
Que nous soyons bloqué par le plafond.

**Screenshots**
https://user-images.githubusercontent.com/40535918/168482719-ad6b6ccb-e4fc-4124-9382-417a83ef1c38.mp4

**Comment by Zino2201** [comment]
Je t'assignes @MaxEstDev mais normalement avec le disque de TP en block ça devrait être vla mieux
