### ISSUE TITLE
[FR] bug pour tirer

### ISSUE THREAD

**Issue by Domdumb** [UpGunGame/UpGun-Issues#250]
**Décrivez le bug**
en jeu, il arrive parfois que on se tire et après certaines manipulation on ne puisse plus tirer ce qui peux être, ma fois, très embêtant 

**Pour reproduire le bug**
Etapes pour reproduire le bug:
1. appuyer sur le bouton pour lancer le couteau
2. faire le grappin casiment en même temp
3. essayer de tirer par après

**Comportement attendu**
ce qui est supposé arriver en fesant cela c'est que une fois que tout est fait, y a une impossibilité de pouvoir tirer  jusqu'à mourir

**Configuration de votre PC:**
 - windows 11
 - Processeur: AMD Ryzen 7 2700X Eight-Core Processor 3.70 GHz
 - RAM: 4x8 GB corsair vengeance  rgb pro 2666 MHz
 - Carte graphique: RTX 3060-TI ASUS OC v.2

**Comment by Zino2201** [comment]
Hmm, sur quelle version? Normalement la 2.0.2.0 règle ça

**Comment by MaxEstDev** [comment]
Oups il manquait un tag, c'est corrigé pour le prochain patch merci !
