### ISSUE TITLE
[FR] Surface glissantes pas si glisssantes

### ISSUE THREAD

**Issue by UnePouleSDF** [UpGunGame/UpGun-Issues#257]
**Version/Mode de jeu**
2.0.2.0 beta

**Décrivez le bug**
Permet de se déplacer sur des surfaces glissantes.

**Pour reproduire le bug**
-Aller sur une surface glissante
-Spammer la touche pour vous accroupir en bougeant

**Screenshots**

https://user-images.githubusercontent.com/105566210/168489757-9414f8a2-1855-4c7e-a3d0-9055b065c036.mp4

**Comment by Zino2201** [comment]
c'est réglé #254
