### ISSUE TITLE
On peu tirer a travers le mur de la grange avec le lance grenade

### ISSUE THREAD

**Issue by OniKirby** [UpGunGame/UpGun-Issues#262]
https://youtu.be/RX0V88HdQZI

**Comment by OniKirby** [comment]
J'ai retester a d'autre endroit sur la map ferme c'est fesable partout

**Comment by MaxEstDev** [comment]
Oh bien vu !
Merci du report je vais voir ça !

**Comment by MaxEstDev** [comment]
C'est corrigé !
Vraiment bien trouvé !
