### ISSUE TITLE
Petit bug? fantôme toujours présent cacher ici

### ISSUE THREAD

**Issue by OniKirby** [UpGunGame/UpGun-Issues#263]
![20220516231059_1](https://user-images.githubusercontent.com/105556234/168720961-71ded08f-df6c-47d7-bfe6-73176b1121f8.jpg)
![20220516231302_1](https://user-images.githubusercontent.com/105556234/168720964-6122e42f-9e14-4a93-b2d2-96d8f69f650a.jpg)

**Comment by ROUPIKS** [comment]
C'est pas un bug c'est un easter egg, je pense que tu peux close.

**Comment by Zino2201** [comment]
Y'a un p'tit fantôme caché sur chaque map :)
