### ISSUE TITLE
BUG! Plat Pétrolière  /Traverser le sol du bat principal/

### ISSUE THREAD

**Issue by Rawin15** [UpGunGame/UpGun-Issues#265]
Version/Mode de jeu:
v2.0.2.0 /UpGun BETA/

Déscription du bug : 
Traverser le sol a partir du sous sol sur la map Plat Pétrolière qui permet de tirer a travers celui-ci et donc spot les gens dans tout le rez-de-chaussée de manière invisible.

Pour reproduire le bug
1.il faut aller au sous sol 
![image](https://user-images.githubusercontent.com/105712824/168782863-44022899-32a4-41e8-a1b2-abafc71bc342.png)

2. Se placer devant les cartons puis sauter dessus EN SE METTANT ACCROUPI :
![image](https://user-images.githubusercontent.com/105712824/168783383-a660c324-5672-4924-af3f-35399f076210.png)

3.se retourner et avancer sur le cabanons vert clair :
![image](https://user-images.githubusercontent.com/105712824/168783979-548a2bfd-479c-4ced-bf58-7a9380cdc6ea.png)

4. tirer a travers le sol:
![image](https://user-images.githubusercontent.com/105712824/168784437-714a1ace-df1b-4fb8-8370-e69ed1be1565.png)

Comportement attendu:
ne pas pouvoir tirer a travers ni voir a travers le sol

Configuration de mon pc:
 - Win 10
 - Intel Core I3-4160
 - RAM: 8 go DDR3
 - Carte graphique: Radeon RX 570 Series

**Comment by MaxEstDev** [comment]
ça sera bon pour le patch !
Merci du report !

**Comment by Rawin15** [comment]
De rien jeune youtobeur en herbe 🐵
