### ISSUE TITLE
[EN] SETTINGS BUG, COLORBLIND MODE DOESN'T SAVE

### ISSUE THREAD

**Issue by yurizgohan** [UpGunGame/UpGun-Issues#267]
**Version/Gamemode**
2.0.0.0/Free for All

**Version**
2.0.0.0 Beta

**Describe the bug**
Basically, i'm colorblind (deutranope) sooo, ingame there is a colorblind correction mode so i enable it.
But when i restart the game this setting is restored and i don't know why..

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Video'
3. Scroll down to 'Colorblind Correction'
4. Choose one of them
5. Restart the game

**Expected behavior**
A normal people would think that data is saved 😳

**Screenshots**
Hmmm, i have a video : [Youtube](https://youtu.be/MNsrgUX4iL4)
Screenshots : ![image_2022-05-17_175145586](https://user-images.githubusercontent.com/105591137/168854602-d3c9aa78-44bc-4997-aee1-b7b4188b5085.png)
![image_2022-05-17_175217081](https://user-images.githubusercontent.com/105591137/168854705-22ddda19-d321-4613-9c86-22ad1729d70b.png)
![image_2022-05-17_175252497](https://user-images.githubusercontent.com/105591137/168854842-9bce172b-f02c-4c96-9a6f-a44c90a35df7.png)

**PC specs:**
 - Operating System: Windows 11 Windows Insider
 - CPU: AMD Ryzen 7
 - RAM: 16
 - GPU: GeForce RTX 2060

**Comment by yurizgohan** [comment]
Contact me on discord : Yuriz#6558

**Comment by MaxEstDev** [comment]
Thanks for the report, i'll patch this right away !

**Comment by MaxEstDev** [comment]
Done !

**Comment by yurizgohan** [comment]
Great thanks for your hard work!!!
