### ISSUE TITLE
[FR] Score disque de tp

### ISSUE THREAD

**Issue by UnePouleSDF** [UpGunGame/UpGun-Issues#271]
**Version/Mode de jeu**
2.0.2.2 beta
**Décrivez le bug**
On peut perdre plusieurs fois des points avec le disque

**Pour reproduire le bug**
-Lancez le disque à un endroit où il pourra atteindre 2 ou plus deadzones dans sa trajectoire

https://user-images.githubusercontent.com/105566210/169026376-032ff069-3300-43bc-876a-485261b2cde4.mp4

**Comment by MaxEstDev** [comment]
Ah oui mdr, je vais voir ça !

**Comment by MaxEstDev** [comment]
C'est patché ! Merci !
