### ISSUE TITLE
[FR] Je sais pas comment le reproduire mais c'est chi*nt

### ISSUE THREAD

**Issue by UnePouleSDF** [UpGunGame/UpGun-Issues#275]
**Version/Mode de jeu**
2.0.2.2 beta

**Décrivez le bug**
apres certaine animation on peut plus tirer, melée ou grenade, malheureusement je n'ai pas plus d'information

**Comment by MaxEstDev** [comment]
what

**Comment by UnePouleSDF** [comment]
genre je me tp et je mets 2 secondes avant de pouvoir tirer, de cut ou de grenade (ça me le fait parfois avec le tir compressé, le slam, le reload ou le respawn)

**Comment by MaxEstDev** [comment]
C'est systematique ?
C'est toi qui host le serveur ?

**Comment by UnePouleSDF** [comment]
c'est pas systématique et c'est moi qui hostait
