### ISSUE TITLE
[FR] Le tooltip des compétences ne se cache pas correctement

### ISSUE THREAD

**Issue by Zino2201** [UpGunGame/UpGun-Issues#277]
**Version/Mode de jeu**
2.0.2.2

**Décrivez le bug**
Le tooltip des compétences ne se cachent pas après que le menu de séléction ait disparu.

**Screenshots**
![image](https://user-images.githubusercontent.com/15857548/169107193-ab2e2c1a-5842-44f3-8d4a-636d28cecda6.png)

**Comment by MaxEstDev** [comment]
oh

**Comment by MaxEstDev** [comment]
J'ai tenté un truc mais vu que c'est rare comme bug on verra bien
Je ferme le report et si on le revoit, on reouvrira, on peut pas le faire sur commande c'est chient
