### ISSUE TITLE
[FR] Les nouvelles statistiques sont buggées

### ISSUE THREAD

**Issue by UnePouleSDF** [UpGunGame/UpGun-Issues#278]
**Version/Mode de jeu**
2.0.2.2 beta

**Décrivez le bug**
Les nouvelles statistiques sont toutes à zero

![Capture d’écran (15)](https://user-images.githubusercontent.com/105566210/169118187-2cd04b4e-8117-4638-a2aa-0ed1ba0a4278.png)

**Comment by Zino2201** [comment]
Yep, elles sont pas encore ajoutées côté Steam c'est pour ça qu'elles sont à zéro
