### ISSUE TITLE
[FR] Personnage trop gros pour prendre une fenetre

### ISSUE THREAD

**Issue by UnePouleSDF** [UpGunGame/UpGun-Issues#279]
**Version/Mode de jeu**
2.0.2.2 beta

**Décrivez le bug**
Dans la version de base on pouvait passer à travers les fenêtres de airsoft mais en beta on peut plus. Je sais pas si c'etait une feature non voulue dans l'ancienne version (j'en doute vu que sur la plateforme petrolière c'est une feature voule) 

**Pour reproduire le bug**
-essayez de passer une fenetre de airsoft

**Comportement attendu**
Pouvoir s'échapper pour survivre au lieu d'etre bloqué dans devant un semi mur invisible et se faire tuer.

**Screenshots**
beta :
https://user-images.githubusercontent.com/105566210/169356144-af8e3f4d-61b4-4765-b84b-371925626f16.mp4

jeu de base sans beta :
https://user-images.githubusercontent.com/105566210/169356154-ea09c035-524f-458f-bb06-cd4ea48ebd4b.mp4

**Comment by MaxEstDev** [comment]
C'es tcorrigé !
