### ISSUE TITLE
[FR] L'XP ne monte pas.

### ISSUE THREAD

**Issue by Matuvu16-16** [UpGunGame/UpGun-Issues#280]
2.0.2.2/Free for All

Quand on fini un match l'XP ne monte pas
(Proposition pourquoi pas mettre à côté du pseudo en match ou dans le lobby le niveau du joueur ?)

**Comportement attendu**
Que l'XP soit gagner une fois un match finit

**Screenshots**
![image_2022-05-19_212252131](https://user-images.githubusercontent.com/67476124/169386173-6dcd4e18-3969-480b-ab20-597b775c4e87.png)

**Comment by MaxEstDev** [comment]
C'est corrigé !
Merci du report !
