### ISSUE TITLE
[FR] Impossible de se TP sur le disque en l'air

### ISSUE THREAD

**Issue by AlexE7Pilou** [UpGunGame/UpGun-Issues#284]
**Version/Mode de jeu**
2.0.2.3

**Décrivez le bug**
Observé sur Ferme, je pouvais pas réactiver mon disque pour me téléporter dessus
Il était sur al touche A, j'ai essayé d'appuyer sur A, E, et F, mais je pouvais pas me TP dessus

**Comment by AlexE7Pilou** [comment]
Jviens de voir que je jouais à UpGun avec un téléchargement en fond, et donc du ping
Ca peut potentiellement venir de là

**Comment by MaxEstDev** [comment]
C'est un problème coté client uniquement
