### ISSUE TITLE
[FR] Pas d'arme dans les mains quand on commence + tir resté enfoncé

### ISSUE THREAD

**Issue by AlexE7Pilou** [UpGunGame/UpGun-Issues#290]
**Version/Mode de jeu**
2.0.2.6/Free for All

**Décrivez le bug**
Observé qu'une fois, pas réussi a le reproduire, mais j'suis pas le seul sur le discord

Quand on a spawn, on avait pas d'arme dans les mains.
De plus, quand j'ai tiré, mon tir était resté enfoncé, jusqu'a ce que je clic une 2e fois

J'ai aps réussi a le reproduire de mon coté, ça doit être client-only

**Screenshots**
https://cdn.discordapp.com/attachments/876115099390214204/984094492095316008/unknown.png de Heisiix sur Discord

**Comment by Celienn** [comment]
Moi cela m'arrive constamment

ici une vidéo d'une game ou cela m'arrive plusieurs fois : 
https://www.youtube.com/watch?v=JLl589xC54w
