### ISSUE TITLE
[FR] Custom nickname fonctione pas

### ISSUE THREAD

**Issue by AlexE7Pilou** [UpGunGame/UpGun-Issues#291]
**Version/Mode de jeu**
2.0.2.6

**Décrivez le bug**
Quand jme rename dans le menu customisation, je suis pas rename in-game, je garde mon pseudo Steam

https://cdn.discordapp.com/attachments/925683214272569394/984097199875051530/2022-06-08_16-09-24.mp4

**Comment by MaxEstDev** [comment]
La fonction a été retirée du coup..Problème résolu ! 😎
