### ISSUE TITLE
[FR] Tir Multiple empêche d'interagir avec les portes d'Everstopped

### ISSUE THREAD

**Issue by AlexE7Pilou** [UpGunGame/UpGun-Issues#299]
**Version/Mode de jeu**
2.0.0.0/Free for All

**Décrivez le bug**
Quand on a tir multiple, taper le boitier n'active pas les portes

ALORS, pendant mon test, j'ai vidé un chargeur, et ça a fini par activer le boitier. Bref, y'a quand même un souci, c'est un peu relou

https://user-images.githubusercontent.com/13340368/172657190-421a4c08-5381-4328-a733-eedc2255695a.mp4

**Comment by MaxEstDev** [comment]
C'est corrigé pour le prochain patch, c'était vraiment une connerie à la con dans mon code
Merci !
