### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Mine846O** [UpGunGame/UpGun-Issues#301]
LoginId:1960a17b4000679ea1dd3baeecf27990
EpicAccountId:3cd9bd0645fb44cba5ed66fa75625735

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000

UpGun_Win64_Shipping!AUpGunDeathmatchGhost::OnCosmeticSettingsUpdated() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Source\UpGun\Deathmatch\UpGunDeathmatchGhost.cpp:227]
UpGun_Win64_Shipping!FTimerManager::Tick()
UpGun_Win64_Shipping!UWorld::Tick()
UpGun_Win64_Shipping!UGameEngine::Tick()
UpGun_Win64_Shipping!FEngineLoop::Tick()
UpGun_Win64_Shipping!GuardedMain()
UpGun_Win64_Shipping!GuardedMainWrapper()
UpGun_Win64_Shipping!WinMain()
UpGun_Win64_Shipping!__scrt_common_main_seh() [d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by Zino2201** [comment]
Je redirige #298
