### ISSUE TITLE
[FR]Crash in game sans aucune raison 

### ISSUE THREAD

**Issue by RylesV1** [UpGunGame/UpGun-Issues#303]
LoginId:a64a20cd4e0c1fb5861937b593fb0140
EpicAccountId:3e3bf3c438e54f649b16d9dea0c77f78

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000

UpGun_Win64_Shipping!AUpGunDeathmatchGhost::OnCosmeticSettingsUpdated() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Source\UpGun\Deathmatch\UpGunDeathmatchGhost.cpp:227]
UpGun_Win64_Shipping!AUpGunDeathmatchGhost::OnRep_PlayerState() [C:\Users\maxlr\Perforce\UpGun_reworked\UpGun\Source\UpGun\Deathmatch\UpGunDeathmatchGhost.cpp:150]
UpGun_Win64_Shipping!UFunction::Invoke()
UpGun_Win64_Shipping!UObject::ProcessEvent()
UpGun_Win64_Shipping!AActor::ProcessEvent()
UpGun_Win64_Shipping!FRepLayout::CallRepNotifies()
UpGun_Win64_Shipping!FObjectReplicator::CallRepNotifies()
UpGun_Win64_Shipping!UActorChannel::ProcessBunch()
UpGun_Win64_Shipping!UActorChannel::ReceivedBunch()
UpGun_Win64_Shipping!UChannel::ReceivedNextBunch()
UpGun_Win64_Shipping!UChannel::ReceivedRawBunch()
UpGun_Win64_Shipping!UNetConnection::ReceivedPacket()
UpGun_Win64_Shipping!UNetConnection::ReceivedRawPacket()
UpGun_Win64_Shipping!USteamSocketsNetConnection::HandleRecvMessage()
UpGun_Win64_Shipping!USteamSocketsNetDriver::TickDispatch()
UpGun_Win64_Shipping!TBaseUObjectMethodDelegateInstance<0,ADefaultPawn,void __cdecl(float),FDefaultDelegateUserPolicy>::ExecuteIfSafe()
UpGun_Win64_Shipping!TMulticastDelegate<void __cdecl(float),FDefaultDelegateUserPolicy>::Broadcast()
UpGun_Win64_Shipping!UWorld::Tick()
UpGun_Win64_Shipping!UGameEngine::Tick()
UpGun_Win64_Shipping!FEngineLoop::Tick()
UpGun_Win64_Shipping!GuardedMain()
UpGun_Win64_Shipping!GuardedMainWrapper()
UpGun_Win64_Shipping!WinMain()
UpGun_Win64_Shipping!__scrt_common_main_seh() [d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll
 - Carte graphique:

**Comment by Zino2201** [comment]
Duplicat de #298
