### ISSUE TITLE
[EN] HUD keeps dissaperaing

### ISSUE THREAD

**Issue by Ginetik1** [UpGunGame/UpGun-Issues#305]
**Version/Gamemode**
2.0.2.8/Free for All-Lobby

**Describe the bug**
Ok, so HUD disappeared completely, only the main menu one keept. Restrting the game wont help the situation.

**To Reproduce**
1. Join a match with all mutators
2. Finish the match
3. Get moved into the lobby
4. Hud is gone.

**Expected behavior**
Hud should be there, it is not even like invisible, as escape and lobby hud wont stop you from moving camera, it just wont open.

**Screenshots**
It was fixed by repeatedly rejoining game and doing some god knows what magic, i dunno how i i did it.

**PC specs:**
 - Operating System: Windows 10
 - CPU:Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz 
 - RAM: 8 GB
 - GPU: GTX 1660 TI

**Comment by Zino2201** [comment]
See #318
