### ISSUE TITLE
[FR] Les cages de foot visible par uniquement la personne qui l'a activé

### ISSUE THREAD

**Issue by Matuvu16** [UpGunGame/UpGun-Issues#309]
**Version/Mode de jeu**
2.0.2.9/Free for All

**Décrivez le bug**
Quand j'ai ouvert les cages de foot j'étais le seul à les voir ouverte et mes potes pouvaient traverser le mur qui est censé ouvrir et on vu ceci (voir screen)

**Pour reproduire le bug**
Etapes pour reproduire le bug:
1. Activer les cages de foot en étant l'hôte.

**Comportement attendu**
Que les cages s'ouvrent pour tout les joueurs

**Screenshots**
![image](https://user-images.githubusercontent.com/67476078/172816640-1d73cccc-5462-422f-b4de-a23db87b65d8.png)

**Comment by MaxEstDev** [comment]
C'est fixé !
