### ISSUE TITLE
[FR] Ecran UwU dans TAB du lobby

### ISSUE THREAD

**Issue by Matuvu16** [UpGunGame/UpGun-Issues#310]
**Version/Mode de jeu**
2.0.2.9/Free for All

**Décrivez le bug**
Quand un joueur rejoins la partie, l'écran affiché sur la touche "TAB" ne correspond pas à son écran dans le jeu
(écran UwU sur TAB et écran Lenny dans la game.

**Pour reproduire le bug**
Etapes pour reproduire le bug:
1. Créer une partie.
2. Regarder sur tab quand un joueur rejoind
3. ...

**Comportement attendu**
Que l'écran affiché soit bon

**Screenshots**
![image](https://user-images.githubusercontent.com/67476078/172817112-f5f62e20-9eef-4e8b-9e08-79b20d4f3009.png)

**Comment by MaxEstDev** [comment]
C'est corrigé pour le prochain patch !
merci !
