### ISSUE TITLE
[FR] Boost local dans le mode de jeu match à mort

### ISSUE THREAD

**Issue by Matuvu16** [UpGunGame/UpGun-Issues#311]
**Version/Mode de jeu**
2.0.2.9/Free for All

**Décrivez le bug**
L'amélioration "Boost local" est disponible dans le mode de jeu "Match à mort classique"

**Comportement attendu**
Qu'elle ne soit pas disponible dans les améliorations en pleine game parmis les 3 choix d'amélioration.

**Screenshots**
![image](https://user-images.githubusercontent.com/67476078/172817533-ae178e98-5a80-400c-bb88-31176440dace.png)

**Comment by MaxEstDev** [comment]
En fait elle permet aussi de te booster donc on l'a laissé finalement
