### ISSUE TITLE
[FR] Bug de Skin

### ISSUE THREAD

**Issue by Matuvu16** [UpGunGame/UpGun-Issues#313]
**Version/Mode de jeu**
2.0.2.9/Free for All

**Décrivez le bug**
J'ai eu un skin avec les lignes verte et le skin noir et les couleurs ce sont inversé dans la nouvelle version du jeu.

**Comportement attendu**
Que les couleurs du skin soit correspondantes

**Screenshots**
![image](https://user-images.githubusercontent.com/67476078/172818974-2e5ad6a9-b594-46cd-abb3-d97a46a0a582.png)
![image](https://user-images.githubusercontent.com/67476078/172818987-42badb8c-8b71-4456-a427-82d7ce00fbf2.png)

**Comment by MaxEstDev** [comment]
C'est bon poour la prochzine maj !
