### ISSUE TITLE
[FR] Amélioration "Pointeur laser" ne fonctionne pas...

### ISSUE THREAD

**Issue by Matuvu16** [UpGunGame/UpGun-Issues#314]
**Version/Mode de jeu**
2.0.2.9/Free for All

**Décrivez le bug**
Quand on a l'amélioration "Pointeur laser" on a pas l'amélioration, le laser ne s'affiche pas.

**Pour reproduire le bug**
Etapes pour reproduire le bug:
1. Equipez-vous de l'amélioration "Pointeur laser"
2. Et lancer le match

**Comportement attendu**
Que l'amélioration fonctionne

![image](https://user-images.githubusercontent.com/67476078/172819957-487715c7-37b3-402b-a5f8-7c44d3acafe4.png)
![image](https://user-images.githubusercontent.com/67476078/172819973-f6616181-5654-44c5-9f59-f544ddc7e01d.png)

**Comment by MaxEstDev** [comment]
Effectivement, le gameplay cue est pas appelé

**Comment by MaxEstDev** [comment]
C'est bon pour le prochain patch !
