### ISSUE TITLE
[FR] La traduction Russe ne fonctionne pas

### ISSUE THREAD

**Issue by Roupiks** [UpGunGame/UpGun-Issues#315]
**Version/Mode de jeu**
2.0.2.9/Free for All

**Décrivez le bug**
La traduction Russe ne fonctionne pas quand on la sélectionne en jeu. Le jeu set met en anglais à la place.

**Pour reproduire le bug**
Options >> Langue >> Russe

**Comportement attendu**
Un jeu qui se traduit en russe.

**Comment by MaxEstDev** [comment]
Oui c'est a venir la traduction a prit du retard
