### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by JuSatorii** [UpGunGame/UpGun-Issues#316]
- arme qui tire tout seul au respawn
- chargeur vidé au respawn
- j'ai choisi la perk du laser et j'ai rien eu
- j'ai passé 3 niveaux et j'ai eu aucun item cosmétique (peut etre dut au fait que je n'ai pas le DLC) et c'était des parties de 10 rounds et j'ai fais premier avec plus de 5k points

**Comment by MaxEstDev** [comment]
L'arme c'est report
Pareil pour le chargeur
Le laser c'est fix
Et les niveau c'est rien à voir
