### ISSUE TITLE
[FR] Resolution de l'écran inchangée

### ISSUE THREAD

**Issue by UnePouleSDF** [UpGunGame/UpGun-Issues#319]
**Version/Mode de jeu**
Beta ouverte

**Décrivez le bug**
Je n'arrive pas à changer la résolution qui est de base à 1920x1080 depuis que je suis passé sur la beta ouverte d'UpGun

**Comportement attendu**
Avoir plus de pixel quand je change à la résolution de base de mon écran soit 2560x1440

**Screenshots**

https://user-images.githubusercontent.com/105566210/173182201-50a80180-237e-4de1-8d8a-32907a943b55.mp4

**Comment by MaxEstDev** [comment]
Et si tu te mets en fenêtré ?

**Comment by UnePouleSDF** [comment]
![image](https://user-images.githubusercontent.com/105566210/173195506-1a4a6a0e-2d3a-40f6-b09c-d513ae76ff26.png)
ça reste comme ça

**Comment by UnePouleSDF** [comment]
https://user-images.githubusercontent.com/105566210/173195571-62f6459c-f816-4548-8914-14731860ee34.mp4

aussi quand je reviens dans "graphics" la résolution reste invchangée

**Comment by UnePouleSDF** [comment]
c'est bizarre, c'est du 2560x1440 que en windowed fullscreen

**Comment by UnePouleSDF** [comment]
mais ça affiche quand meme 1024x768

**Comment by UnePouleSDF** [comment]
bon ça remarche mais je sais pas ce que j'ai fais

**Comment by UnePouleSDF** [comment]
https://user-images.githubusercontent.com/105566210/173196027-0e384edc-0de0-44a3-9143-8c336b865771.mp4

ok j'ai trouvé le problème : il y a 2 fois les résolutions et l'une des deux ne marche pas

**Comment by MaxEstDev** [comment]
Merci bcp c'est corrigé !
