### ISSUE TITLE
[FR] Achievement Couteau Pointu obetenu après 1 tier de Couteau Pointu

### ISSUE THREAD

**Issue by AlexE7Pilou** [UpGunGame/UpGun-Issues#330]
**Décrivez le bug**
Tout est dans le titre
J'ai fait une game full-couteau avec des gens. J'ai pris 1x l'amélio couteau pointu.
Et a la fin, j'ai obtenu l'achievement Couteau très pointu, normalement c'est quand on a plusieurs tier de Couteau Pointu, or j'en avais qu'un seul

![Capture d’écran 2022-06-16 110619](https://user-images.githubusercontent.com/13340368/174035252-797a457b-376b-483e-9f98-0717f90ec678.png)

**Comment by MaxEstDev** [comment]
C'est patché !
