### ISSUE TITLE
Grey screen at start with everymap

### ISSUE THREAD

**Issue by drdre1973** [UpGunGame/UpGun-Issues#332]

**Comment by drdre1973** [comment]
game screen is grey as its in full zoom modus, or like you crashed into a wall
Spectator modus is ok .

https://user-images.githubusercontent.com/11754822/174109350-bdd0f654-3344-43f5-85e6-a3ef187d4016.mp4

**Comment by MaxEstDev** [comment]
Hey !
You can't event see in the lobby.
Have you tried reistalling the game ? Because the game do not seem to save your language

**Comment by MaxEstDev** [comment]
I think your save is corrupt and the game gives you a FOV of 0

**Comment by MaxEstDev** [comment]
Hey this is the case, just delete your save fgrom the appdata folder :)
