### ISSUE TITLE
impossible de tirer quand on utilise tir chargé et glissade

### ISSUE THREAD

**Issue by Arkkahoss** [UpGunGame/UpGun-Issues#342]
quand on utilise une glissade pendant l'animation de chargement de tir chargé (où mr le robot écrase l'avant de son fusils), on bug et on peut rien faire à part bouger sauter et utiliser la glissade. les armes, les autres capas, les tirs secondaires etc... sont inutilisables et la seule solution pour sortir de cet état est de mourir.
plutot embétant

**Comment by MaxEstDev** [comment]
C'était y'a combien de temps ?

**Comment by MaxEstDev** [comment]
C'était y'a 2 semaines, c'est réglé !
