### ISSUE TITLE
[FR] Bug du boost local (Je pense)

### ISSUE THREAD

**Issue by Matuvu16** [UpGunGame/UpGun-Issues#344]
**Version/Mode de jeu**
2.0.3.0e/Free for All

**Décrivez le bug**
J'ai l'impression que le boost local ne fonctionne pas en game (j'ai tester dans le mode de jeu "match à mort")
Je fais pas plus de dégat, pas de cercle jaune sous les pied du robot.

**Pour reproduire le bug**
Etapes pour reproduire le bug:
1. Utiliser le boost local

**Comportement attendu**
Mettre en place le cercle jaune sous nos pied et mettre les effets de cette amélioration ou l'enlever dans ce mode de jeu.

**Screenshots**
https://i.gyazo.com/39217bf0421c41a69a5b1109dfba25d7.gif

**Comment by MaxEstDev** [comment]
C'était effectivement pas bon C'est corrigé, merci !
