### ISSUE TITLE
[FR] Visuel Câble dans la plateforme pétrolière

### ISSUE THREAD

**Issue by Matuvu16** [UpGunGame/UpGun-Issues#345]
**Version/Mode de jeu**
2.0.3.0e/Free for All

**Décrivez le bug**
Des câbles dépassent du mur xD

**Screenshots**
![image](https://user-images.githubusercontent.com/67476078/174447161-f89cc264-d31d-4816-9373-c46b2b60c748.png)

**Comment by MaxEstDev** [comment]
ah oui giga grave !
