### ISSUE TITLE
[FR] Beaucoup d'armes secondaires

### ISSUE THREAD

**Issue by UnePouleSDF** [UpGunGame/UpGun-Issues#354]
**Version/Mode de jeu**
2.0.3.0e

**Décrivez le bug**
On peut avoir beaucoup d'arme secondaire dans le choix des améliorations

**Pour reproduire le bug**
1) Mettre toutes les armes secondaires au tier 1 sur le menu des choix d'amélioration
2) Augmenter autant qu'il en faut

**Screenshots**

https://user-images.githubusercontent.com/105566210/174683763-50e35cc5-38fc-4bf9-8415-112217ff9b9f.mp4

Lors d'une prise (que j'ai raté) le cappage des armes secondaires était enlevé, j'ai pu avoir Lance grenade tier 3, laser Tier 3 et pompe Tier 3

**Comment by MaxEstDev** [comment]
Merci du report !
C'est corrigé !
(tellement chiant à faire :( )
