### ISSUE TITLE
[FR] Crash 

### ISSUE THREAD

**Issue by UnePouleSDF** [UpGunGame/UpGun-Issues#356]
**Version/Mode de jeu**
Version derniere

**Décrivez le bug**
J'étais en partie avec un USA, il a dit qu'il lui manquait son arme puis j'ai crash

**Screenshots**
![Capture d’écran (25)](https://user-images.githubusercontent.com/105566210/175073151-96c65dda-13c5-4f5d-a50f-bf1f68a80de1.png)

**Comment by MaxEstDev** [comment]
Salut !
Sans le texte du crash on peut rien faire faire du tout là :(
Y'a oyen de récupérer le texte ?

**Comment by UnePouleSDF** [comment]
J'ai vérifié dans les CrashReport, le seul fichier modifié à l'heure du crash sont :

**Comment by UnePouleSDF** [comment]
je te l'envois sur discord
