### ISSUE TITLE
[FR] Amélioration "Grenade Post mortem" ne fonctionne pas

### ISSUE THREAD

**Issue by Matuvu16** [UpGunGame/UpGun-Issues#357]
**Version/Mode de jeu**
2.0.3.1/Free for All

**Décrivez le bug**
L'amélioration de grenade post mortem ne fonctionne pas.

**Pour reproduire le bug**
Etapes pour reproduire le bug:
1. Equiper l'amélioration par défaut et voilà

**Comportement attendu**
Que l'amélioration fonctionne

**Comment by MaxEstDev** [comment]
C'est fix wtf je comprends pas pourquoi ça a sauté
