### ISSUE TITLE
[FR] Pas d'image sur les succès :/

### ISSUE THREAD

**Issue by Matuvu16** [UpGunGame/UpGun-Issues#359]
**Version/Mode de jeu**
2.0.3.1/Free for All

**Décrivez le bug**
Les 2 nouveaux succès n'ont pas d'image.

**Screenshots**
![image](https://user-images.githubusercontent.com/67476078/175081320-e4f6790c-40bb-4ead-a58e-9ce089c1ce3e.png)

**Comment by MaxEstDev** [comment]
C'est corrigé !
