### ISSUE TITLE
[FR] Grenadeception fonctionne pas 

### ISSUE THREAD

**Issue by AlexE7Pilou** [UpGunGame/UpGun-Issues#36]
**Décrivez le bug**
Pas de seconde grenade avec grenadeception
J'avais un doute depuis le début, mais après avoir pris Grenade antigravité, et observer attentivement ma grenade, pas de 2e explosion

**Comportement attendu**
Big boom, then big boom 2

**Comment by MaxEstDev** [comment]
A retester

**Comment by MaxEstDev** [comment]
On a testé avec Tim, ça marche, sauf quand avec grenades reactives quand la première explose au contact d'une surface ; la seconde est spawn mais dispawn avant d'exploser si elle ne touche rien

**Comment by MaxEstDev** [comment]
C'est corrigé, le soucis venait des grenades reactives qui en spawnant considérées parfois être touchées et annulaient donc l'explosion
