### ISSUE TITLE
[FR] Succès Polyvalent

### ISSUE THREAD

**Issue by Matuvu16** [UpGunGame/UpGun-Issues#361]
**Décrivez le bug**
Le succès Polyvalent ne marche pas (pas d'image, pas de description)
Même si c'est un succès caché on voit pas.

**Comportement attendu**
Que le succès fonctionne et que l'image apparaisse.

**Screenshots**
![image](https://user-images.githubusercontent.com/67476078/175265212-53ebafdc-fa7d-45dc-902d-5b0ce834a4a9.png)

**Comment by MaxEstDev** [comment]
ENFIN
