### ISSUE TITLE
[FR] Invinsibilité dans l'eau

### ISSUE THREAD

**Issue by Matuvu16** [UpGunGame/UpGun-Issues#368]
**Version/Mode de jeu**
2.0.3.1b/Free for All

**Décrivez le bug**
Avec l'amélioration "Boost local" on est invinsible quand on va dans l'eau de la plateforme pretrolière, par la suite on peut rester longtemps sous l'eau

**Pour reproduire le bug**
Etapes pour reproduire le bug:
1. Activer boost local
2. Plonger dans l'eau

**Comportement attendu**
Que l'eau nous tue et que le boost local ne fasse pas cet effet

**Screenshots**
https://i.gyazo.com/e8f9e2b2963b72f0403873b1de198752.gif
 
![image](https://user-images.githubusercontent.com/67476078/176489103-97b38b12-2dfe-4617-a275-b5a7676548d9.png)

**Comment by MaxEstDev** [comment]
C'est corrigé !
