### ISSUE TITLE
Bouclier bug quand barre de vie boostée [FR]

### ISSUE THREAD

**Issue by Barnabrou** [UpGunGame/UpGun-Issues#369]
J'ai récupéré l'amélioration Barre de vie boostée. A ma réapparition ma vie descendait progressivement jusqu'à 100 au lieu de 125. es-ce normal ?

**Comment by MaxEstDev** [comment]
ça de vrait être fix d'ici qqls jours ! :)

**Comment by MaxEstDev** [comment]
#360
