### ISSUE TITLE
[FR] Crampons Non ReglementesBroken

### ISSUE THREAD

**Issue by UnePouleSDF** [UpGunGame/UpGun-Issues#373]
**Version/Mode de jeu**
Derniere version

**Décrivez le bug**
Les Crampons peuvent tuer quelqu'un meme si le joueur qui l'a ne bouge pas 

**Pour reproduire le bug**
-Avoir les crampons
-Se mettre de facon que nos pieds soient un peu en l air
-L'autre joueur passe

Pour le screenshot ca bug donc il ne faut pas compter la dessus

**Comment by MaxEstDev** [comment]
Je comprends pas comment tu te places pour reproduire le bug

**Comment by UnePouleSDF** [comment]
Sinon je te montre ingame

**Comment by MaxEstDev** [comment]
je comprends pas, pourquoi y'a pas moyen de le record ?

**Comment by UnePouleSDF** [comment]
Je suis pas chez moi donc j'ai pas mon pc, donc j'emprunte un ordi mais OBS marche pas
