### ISSUE TITLE
[FR] WaterCooling Inutile

### ISSUE THREAD

**Issue by UnePouleSDF** [UpGunGame/UpGun-Issues#376]
**Version/Mode de jeu**
Derniere version du jeu

**Décrivez le bug**
Sans et avec Watercooling les degats du feu sont les memes

**Experience menee**
-Exploser baril explosif dde Plateforme Petroliere
-Se mettre dans le feu cause
-Attendre de prendre des degats puis sortir du feu
-Attendre qu'on ne soit plus enflamme

9 de degat en moyenne (4x repete) avec et sans Watercooling

**Comment by MaxEstDev** [comment]
C'est corrigé, les dégâts sont à présent amoindrit également sur les effets de brulures !
