### ISSUE TITLE
[FR]Les mannete ps3/xbox360 ne fonctione pas

### ISSUE THREAD

**Issue by garloulou2507** [UpGunGame/UpGun-Issues#378]
**Version/Mode de jeu**
2.0.3.3/Free for All

**Décrivez le bug**
En branchant un mannete ps3 (convertie en mannete 360 pas scp server) ou une mannete xbox 360 la mennete est pas reconnue par le jeu

**Pour reproduire le bug**
Etapes pour reproduire le bug:
1. brancher un mannete xbox 360 (ou ps3
(falcutatif) 2. convertire sa mannete ps3 en mannete xbox 360
3.lancer upgun est constater que la mannete est pas la 

**Comportement attendu**
pouvoire jouer a upgun avec une mannete

**Comment resoudre le bug**
redemare le jeu sans la mannete de brancher
puis lancer un game puis brancher votre mannete

**Comment by MaxEstDev** [comment]
Salut !
Je ne pense pas qu'on commence à supporter les manettes de ps3 (elles ont 15ans) 
Par contre, je peux te conseiller un soft genre https://joytokey.net/en/ pour pouvoir jouer :)
