### ISSUE TITLE
[EN]

### ISSUE THREAD

**Issue by maysxrawz** [UpGunGame/UpGun-Issues#379]
2.0.3.4/Free for All

2.0.3.4

Some achievements aren't possible like getting 5K score in one game because the game doesn't take 
biggest score as a stat i believe and you can't complete the use skills 0/78 (screenshot down)

1. Go to the main menu
2. Click on statistics 
3. first and fourth line 

I don't know why this isn't working, but i love completing 100% achievements on steam game when i like them so it's kinda sad for me

![image](https://user-images.githubusercontent.com/114577943/192758780-0b35f323-7c4e-4cb5-9f36-e2be130f7930.png)
![image](https://user-images.githubusercontent.com/114577943/192758810-db896657-bb48-4af9-aa95-7334c9dd5108.png)
![image](https://user-images.githubusercontent.com/114577943/192758838-8490cb84-bc84-4425-9c12-3f0451858c73.png)
![image](https://user-images.githubusercontent.com/114577943/192758851-6bfa2bad-9cb7-4bff-a4ba-91e0f6619433.png)

**PC specs:**
 - Operating System: windows
 - CPU:Ryzen 5
 - RAM:8
 - GPU:Geforce 1050ti

**Comment by MaxEstDev** [comment]
Hey !
We'll try to fix this again !

**Comment by MaxEstDev** [comment]
The achiement for equiping is fixed but the other has another bug report, 'ill keep the other report !
Thanks !
