### ISSUE TITLE
Erreurs dans les descriptions des items

### ISSUE THREAD

**Issue by Saquebutte** [UpGunGame/UpGun-Issues#386]
![image](https://user-images.githubusercontent.com/119077064/204048430-5d4ecb6a-291d-4afa-b08e-994725682643.png)
![image](https://user-images.githubusercontent.com/119077064/204048436-de0a61ec-d15e-4738-930a-70076b904be0.png)
![image](https://user-images.githubusercontent.com/119077064/204048442-bdb24d79-7f9d-4421-b7ad-45344d899899.png)
![image](https://user-images.githubusercontent.com/119077064/204048449-8979442f-ec93-4f66-9517-70f715a3d8a4.png)
![image](https://user-images.githubusercontent.com/119077064/204048451-1dea8af6-86c2-4038-b750-2ace45301d80.png)
![image](https://user-images.githubusercontent.com/119077064/204048455-28c572ee-99c4-4f57-9434-a81d66579614.png)
![image](https://user-images.githubusercontent.com/119077064/204048461-ee6e2d4e-9df0-460a-943f-095e5cb3fc98.png)
![image](https://user-images.githubusercontent.com/119077064/204048466-841b1c1d-3e5e-49fa-a526-38792983f863.png)
![image](https://user-images.githubusercontent.com/119077064/204048477-de1112ee-6deb-4dcc-9d07-3a75f81f10f3.png)
![image](https://user-images.githubusercontent.com/119077064/204048474-5c77eb9d-a5ea-43c8-81c4-b21206964a78.png)

**Comment by MaxEstDev** [comment]
J'ai adressé ttes les fautes mais pour les tags c'ets pazs possible pour le moment :x
