### ISSUE TITLE
[FR] Bug D'amelioration

### ISSUE THREAD

**Issue by wonderbloc** [UpGunGame/UpGun-Issues#390]
**Version/Mode de jeu**
Version sans DLC

**Décrivez le bug**
Il est possible d'utiliser des amélioration dans le lobby ce qui peut être problématique car le jump devient beaucoup plus facile avec le grappin par exemple  

**Pour reproduire le bug**
Etapes pour reproduire le bug:
1. lancer une partie 
2. la configurer de manière a ce quelle soit la plus courte possible
3. choisir les améliorations voulu
4. terminer la partie
5. appuyer sur "Changer les paramètres"

**Comportement attendu**
Les amélioration mis par défaut pourront être utiliser dans le lobby  

Notes* les amélioration récupérer dans la partie ne semble pas être affecter par ce bug. Donc seul 5 améliorations pourront être utiliser 

**Screenshots**
Si possible, un screenshot pour visualiser le bug.
![Capture d’écran 2022-12-04 124521](https://user-images.githubusercontent.com/119789456/205488532-6addc007-7f37-44cd-bfd9-5347a1044a28.png)

**Comment by MaxEstDev** [comment]
Merci pour le report !
ça sera adressé !

**Comment by MaxEstDev** [comment]
C'est adressé !
