### ISSUE TITLE
[FR] Remarques skins de chapeau

### ISSUE THREAD

**Issue by Saquebutte** [UpGunGame/UpGun-Issues#392]
![image](https://user-images.githubusercontent.com/119077064/206730239-be80b74d-e7e2-459c-98ce-d8f357729aa8.png)
![image](https://user-images.githubusercontent.com/119077064/206730252-77f55959-adf2-4ddf-8a1c-2ebd165c94b3.png)
![image](https://user-images.githubusercontent.com/119077064/206730264-aa78c690-8d81-46c4-8ac8-626397d1f56e.png)
![image](https://user-images.githubusercontent.com/119077064/206730272-43d63e9c-c65e-472d-9393-825a3a9e8065.png)
![image](https://user-images.githubusercontent.com/119077064/206730281-a852f62d-a943-47a6-8dba-2be75e76c61f.png)
![image](https://user-images.githubusercontent.com/119077064/206730284-973e8441-b356-477a-9f3a-dbac744ef29f.png)
![image](https://user-images.githubusercontent.com/119077064/206730294-a34bdcbb-8d86-4e80-b76e-7710eb5254a0.png)
![image](https://user-images.githubusercontent.com/119077064/206730313-c86d3e63-a586-4c45-a7c7-2a2030adad2f.png)
![image](https://user-images.githubusercontent.com/119077064/206730324-55faff1a-412b-46f4-93df-b615432ae6ce.png)
![image](https://user-images.githubusercontent.com/119077064/206730330-3667a593-44b2-4f87-83f2-52453b263e30.png)
![image](https://user-images.githubusercontent.com/119077064/206730342-7ffb33b1-f079-49ed-855a-ab3bdda42c71.png)
![image](https://user-images.githubusercontent.com/119077064/206730352-e01a037f-c5cf-4377-aff4-dd2cf5716d38.png)
![image](https://user-images.githubusercontent.com/119077064/206730359-5f2bb3e7-23b6-41de-ba41-0285c85e6f25.png)

**Comment by MaxEstDev** [comment]
C'est bon !
