### ISSUE TITLE
[FR] Remarques skins de fusils 2/2

### ISSUE THREAD

**Issue by Saquebutte** [UpGunGame/UpGun-Issues#396]
![image](https://user-images.githubusercontent.com/119077064/206741131-e2a049a8-41e8-466b-950e-78d7b387591b.png)
![image](https://user-images.githubusercontent.com/119077064/206741185-006cd8f5-15f9-4281-8cdf-9fb47cdbb48a.png)
![image](https://user-images.githubusercontent.com/119077064/206741194-ec41ef1b-8e04-47c4-be46-cb94e4833e95.png)
![image](https://user-images.githubusercontent.com/119077064/206741201-0bdfe08d-56f2-4cfe-a44f-6bcbc6bb1f7b.png)
![image](https://user-images.githubusercontent.com/119077064/206741206-d925c623-8cbd-4598-a1c1-ad306639e6b1.png)
![image](https://user-images.githubusercontent.com/119077064/206741212-02df5770-66d1-4a83-a9af-7df8294d7f0e.png)
![image](https://user-images.githubusercontent.com/119077064/206741218-d13901e5-c7bf-4777-8f30-3a057660667d.png)
![image](https://user-images.githubusercontent.com/119077064/206741226-ba48ace6-5864-4267-8345-93639607a908.png)
![image](https://user-images.githubusercontent.com/119077064/206741232-085c9790-3ff1-4b57-87b0-4ae132acc886.png)
![image](https://user-images.githubusercontent.com/119077064/206741242-a227dcd3-3ec5-479e-99dc-dac5b3a054ba.png)
![image](https://user-images.githubusercontent.com/119077064/206741247-d45e41aa-ec12-4412-90f0-aa620593beab.png)
![image](https://user-images.githubusercontent.com/119077064/206741254-d59f1863-6643-4098-9bfd-b94c0ad84438.png)
![image](https://user-images.githubusercontent.com/119077064/206741262-7d8b77e0-47ce-4a07-9781-d4952db72f9c.png)
![image](https://user-images.githubusercontent.com/119077064/206741268-d4097a0f-3823-4804-a2db-3ad359533749.png)
![image](https://user-images.githubusercontent.com/119077064/206741276-b7efb86b-8c61-43d6-b0e3-1b422816ac9f.png)
![image](https://user-images.githubusercontent.com/119077064/206741286-28cccf8c-4e84-4277-9d77-541ce7fa6076.png)
![image](https://user-images.githubusercontent.com/119077064/206741293-90325dad-69bd-4e6f-b925-eb3038ec376d.png)

**Comment by MaxEstDev** [comment]
Il me semble que je l'avais fais mais jamais validé
