### ISSUE TITLE
[FR] Bug graphique écran d'accueil

### ISSUE THREAD

**Issue by Saquebutte** [UpGunGame/UpGun-Issues#400]
**Version/Mode de jeu**
v2.0.3.5b / Ecran d'accueil

**Décrivez le bug**
Les boutons de sélection "clignotent".

**Pour reproduire le bug**
Laisser la souris sur le bord gauche du bouton.

**Comportement attendu**
Le bouton va se mettre à clignoter rapidement.
https://user-images.githubusercontent.com/119077064/207915509-18d42e21-c1d2-42a5-85ca-30e11ad96286.mp4

**Comment by MaxEstDev** [comment]
👀 
J'ai suite à la nouvelle maj pu corrigé ça, merci du report !
