### ISSUE TITLE
[FR] Bug de collision avec des citrouilles

### ISSUE THREAD

**Issue by Saquebutte** [UpGunGame/UpGun-Issues#404]
Version/Mode de jeu
v2.0.3.5b / FFA

Décrivez le bug
Les citrouilles de l'event d'halloween restent sur la map et engendrent des bugs de collision.

Pour reproduire le bug
Inconnu (certaines personnes semblent l'avoir mais pas tout le monde). Ce bug ne semble pas être lié a l'host.

Comportement attendu
Les citrouilles restent sur la map et les personnes qui marchent dessus ont des comportement bizarre dans la vue du joueur qui peut tjr voir les citrouilles. 

https://user-images.githubusercontent.com/119077064/207918466-5ccfbec4-4ef0-48b7-ada2-2650d8f78b6a.mp4

**Comment by MaxEstDev** [comment]
ça normalement c'est bon ça sera à vérifier avec la maj !
