### ISSUE TITLE
[FR] Bug de collision avec les chapeaux des joueurs

### ISSUE THREAD

**Issue by Saquebutte** [UpGunGame/UpGun-Issues#405]
Version/Mode de jeu
v2.0.3.5b / FFA

Décrivez le bug
Lorsqu'un joueur meurt, son chapeau reste sur la carte, ce qui peut engendrer des bugs de collision.

Pour reproduire le bug
Marcher sur un chapeau.

Comportement attendu
Projection suivant la direction précédente. (peut être une multiplication du vecteur vitesse?)

https://user-images.githubusercontent.com/119077064/207919340-92bd8773-aded-4684-b89a-0def96be9df6.mp4

**Comment by MaxEstDev** [comment]
J'avais comme oublié celui là
