### ISSUE TITLE
[FR] Bug animation couteau brochette de boeuf

### ISSUE THREAD

**Issue by Saquebutte** [UpGunGame/UpGun-Issues#411]
Version/Mode de jeu
v2.0.3.6- / Partout

Décrivez le bug
Le couteau brochette de boeuf gère mal la tomate lors de l'animation du cut.

Pour reproduire le bug
Il suffit d'équiper le couteau brochette de boeuf et de faire un coup de couteau.

Comportement attendu
La tomate vole sans être rattachée au couteau.

https://user-images.githubusercontent.com/119077064/209227898-40e2ea95-464e-4139-a35b-4052295aed0c.mp4

**Comment by MaxEstDev** [comment]
ENFIN
