### ISSUE TITLE
[EN]

### ISSUE THREAD

**Issue by SKR1NiX** [UpGunGame/UpGun-Issues#412]
**Version/Gamemode**
2.0.0.0/Free for All

**Version**
2.0.0.0

 
You can reduce the font in Russian translation to normally press the network button

**PC specs:**
 - Operating System:win 11 (p)
 - CPU: i5-6500
 - RAM:16
 - GPU:Rx470 8gb
![image](https://user-images.githubusercontent.com/67193919/209400941-4f9cfccc-9d3e-4ef1-9b97-4f45d3a566ec.png)

**Comment by MaxEstDev** [comment]
Hi sorry for the delay
Reducing the font isn't much of an option
I'll find a solution but do you know a better translation that would be shorter ?
