### ISSUE TITLE
[FR]sol everstopped manque les colision pour les tir

### ISSUE THREAD

**Issue by supertails120** [UpGunGame/UpGun-Issues#415]
**Version/Mode de jeu**
2.0.3.6/Free for All

**Décrivez le bug**
sur everstoped a un endroit de la map les balle passe le sol comme si de rien était

**Pour reproduire le bug**
Étapes pour reproduire le bug:
vidéo qui montre le bug
https://user-images.githubusercontent.com/106885031/236210320-2148dac8-8292-4452-86ab-8fe20a5c40dd.mp4

**Comportement attendu**
les balles font un impact.

**Comment by MaxEstDev** [comment]
![image](https://github.com/UpGunGame/UpGun-Issues/assets/96690800/d82edff0-5b44-4e02-b660-db00d8ff7845)
Je ne parviens pas à reproduire le bug, ça te fait systématiquement ?

**Comment by supertails120** [comment]
j'ai lancer le jeu pour re tester et le bug ne se produit plus.
