### ISSUE TITLE
[FR]Clone ne prend pas les mutateurs

### ISSUE THREAD

**Issue by UnePouleSDF** [UpGunGame/UpGun-Issues#418]
**Version/Mode de jeu**
2.0.3.6

**Décrivez le bug**
Le clone n'a pas la grosse tete alors qu'on est en Mutation "grosse tete"

**Comportement attendu**
Le clone prend la mutation

**Screenshots**
![Capture d'écran 2023-06-15 143845](https://github.com/UpGunGame/UpGun-Issues/assets/105566210/f2c5d4cc-942e-49d4-ad3b-433f5873bdf2)

**Comment by MaxEstDev** [comment]
C'est patché merci !
ça sera bon dans la prochaine maj !
