### ISSUE TITLE
[FR] Fautes de frappe achievement "Chirurgie Laser" en anglais

### ISSUE THREAD

**Issue by lucas-martinati** [UpGunGame/UpGun-Issues#438]
**Version/Mode de jeu**
2.0.0.0/Free for All

**Décrivez le bug**
[Trouver par Poulpo] Il y à une faute de frappe sur le nom de l'achievement "Chirurgie Laser" en anglais qui est "Lasik surgery",
et sur le mots "target" de la description du même achievement 

**Comportement attendu**
Il devrait être écrit "Laser surgery" pour le nom et "Hit multiple targets at once with your laser." pour la description

**Screenshots**
![image](https://github.com/UpGunGame/UpGun-Issues/assets/127530926/5ff72188-fe75-4e6f-812d-951c4527b8aa)

**Comment by MaxEstDev** [comment]
J'avais bien oublié le S merci
Mais LASIK c'est un nom de chirurchie au laser, c'était correct
