### ISSUE TITLE
[FR] Bug preview couteux laser

### ISSUE THREAD

**Issue by Saquebutte** [UpGunGame/UpGun-Issues#446]
**Version/Mode de jeu**
2.0.0.0/Free for All

Petit problème de rien du tout avec les 2 couteaux laser qui ont une image identique. (Le couteau laser bleu devrait avoir une lame bleue sur la preview).
![image](https://github.com/UpGunGame/UpGun-Issues/assets/119077064/c35fccc1-e2bb-400e-9c7f-a98b33def864)

**Comment by MaxEstDev** [comment]
AH ! Je vais aller investiguer ça !

**Comment by MaxEstDev** [comment]
C'est tout corrigé !
