### ISSUE TITLE
[FR] Bug couteau pointu T2

### ISSUE THREAD

**Issue by Saquebutte** [UpGunGame/UpGun-Issues#448]
**Version/Mode de jeu**
2.0.0.0/Free for All

**Décrivez le bug**
Les dégâts du couteau pointu ne fonctionnent pas comme il le devrait.
Le couteau devrait normalement faire : 
- sans couteau pointu -> 80 dégâts
- avec couteau pointu T1 -> 130 dégâts
- avec couteau pointu T2 -> 999 dégâts
Cependant, les dégâts du couteau avec couteau pointu T1 et T2 sont identiques (130)

**Pour reproduire le bug**
Equiper couteau pointu T2 et frapper son adversaire, les dégâts sont de 130.

**Comportement attendu**
Le couteau devrait pouvoir one-shot les adversaire quoi qu'il arrive lorsqu'il est amélioré au maximum. (donc faire 999 dégâts)

**Comment by MaxEstDev** [comment]
chelou j'irai voir !

**Comment by MaxEstDev** [comment]
j'ai pas vu le temps passer !
C'est patché !
