### ISSUE TITLE
[FR] Inventaire Steam

### ISSUE THREAD

**Issue by ZNS-Dev** [UpGunGame/UpGun-Issues#457]
**Version/Mode de jeu**
2.0.5.0/Free for All

**Décrivez le bug**
Il manque le trie "Couteau"

**Screenshots**
![image](https://github.com/UpGunGame/UpGun-Issues/assets/118850856/fcb3dcdd-6979-4145-bf65-7b1a4dae6220)

**Comment by MaxEstDev** [comment]
C'est bon ! Merci !
