### ISSUE TITLE
[FR] Interface du lobby qui est visible même quand l'interface est fermée

### ISSUE THREAD

**Issue by ramok0** [UpGunGame/UpGun-Issues#461]
**Version/Mode de jeu**
2.0.5.0/Free for All

**Décrivez le bug**
Quand on ferme le menu de configuration du lobby, on voit toujours le nom de la partie (si il est assez long), donc le menu est toujours rendu par le jeu alors qu'il est fermé

**Pour reproduire le bug**
Etapes pour reproduire le bug:
1. Mettre un nom de partie assez long
2. Ouvrir le menu
3. Fermer le menu

**Comportement attendu**
Le menu ne devrait pas être rendu par le jeu

**Screenshots**
![image](https://github.com/UpGunGame/UpGun-Issues/assets/63268168/cbda014f-29e9-4b07-93de-60d5ecfd765b) (le nom qui depasse)
![image](https://github.com/UpGunGame/UpGun-Issues/assets/63268168/956bfbdb-e742-442a-93c3-63620bc1ccc7) (menu normal)

**Comment by ramok0** [comment]
Les screenshots se sont pas affichés d'accord...
l'interface normal =>
![image](https://github.com/UpGunGame/UpGun-Issues/assets/63268168/be9afc00-4ec1-48a1-ae75-81ffcc0d466e)

le probleme
![image](https://github.com/UpGunGame/UpGun-Issues/assets/63268168/28b86822-43c0-44a8-aa57-503bda7ae3b2)

**Comment by MaxEstDev** [comment]
Merci !
C'est patché !
