### ISSUE TITLE
[EN] Shadow of knife attack doesn't match animation

### ISSUE THREAD

**Issue by bfoy** [UpGunGame/UpGun-Issues#462]
**Version/Gamemode**
2.0.5.0/all game modes

**Version**
2.0.5.0

**Describe the bug**
When attacking with your knife, the shadow animation that plays does not match the animation the player sees. The shadow animation always appears to be the same as if the player had one level of Knife's Out

**To Reproduce**
Steps to reproduce the behaviour:
1. Attack with the knife  where you can see your shadow
2. See error

**Screenshots**
![image](https://github.com/UpGunGame/UpGun-Issues/assets/26540748/1cb53d55-565b-4410-ac31-aea36c6a6fe2)

**PC specs:**
 - Operating System: Windows
 - CPU: Ryzen 7
 - RAM: 32 GB
 - GPU: GTX 1650

**Comment by ZNS-Dev** [comment]
It's not a bug

**Comment by bfoy** [comment]
K

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
