### ISSUE TITLE
[FR] Traduction FR

### ISSUE THREAD

**Issue by ZNS-Dev** [UpGunGame/UpGun-Issues#465]
**Version/Mode de jeu**
2.0.5.0

**Comportement attendu**
Mutator au lieu de Mutateur

**Screenshots**
![image](https://github.com/UpGunGame/UpGun-Issues/assets/118850856/f806fc08-df88-4f44-8248-40cdf3770574)

**Comment by MaxEstDev** [comment]
C'est patché !
