### ISSUE TITLE
[FR] écran Sand fond pas traduit

### ISSUE THREAD

**Issue by ZNS-Dev** [UpGunGame/UpGun-Issues#472]
**Version/Mode de jeu**
2.0.0.0/Free for All

**Décrivez le bug**
Manque la traduction pour cette écran en anglais.

**Screenshots**
![image](https://github.com/UpGunGame/UpGun-Issues/assets/118850856/300fe8ba-6306-4b24-a8dc-0f31e9effd27)

**Comment by MaxEstDev** [comment]
C'est bon ! (ça sera patch à la prochaine maj)
