### ISSUE TITLE
[FR] Porte pas pris en compte avec Fantôme

### ISSUE THREAD

**Issue by ZNS-Dev** [UpGunGame/UpGun-Issues#475]
**Version/Mode de jeu**
2.0.5.1

**Décrivez le bug**
La porte s'ouvre pas car on est en fantôme.

**Comportement attendu**
Porte qui s'ouvre pas en étant fantôme.

**Screenshots**
https://github.com/UpGunGame/UpGun-Issues/assets/118850856/3e4ab2c0-049a-4488-b7ba-b4570fc1de38

**Comment by MaxEstDev** [comment]
C'est prévu comme ça :)
