### ISSUE TITLE
[FR] Image map

### ISSUE THREAD

**Issue by ZNS-Dev** [UpGunGame/UpGun-Issues#478]
**Version/Mode de jeu**
2.0.5.1

**Décrivez le bug**
L'image de la Plateforme Pétrolière n'est pas a jour

**Comportement attendu**
Image pas a jour

**Screenshots**
![Map_TN_PP](https://github.com/UpGunGame/UpGun-Issues/assets/118850856/3ad146dc-179d-4cc6-b622-fc501396dd9b)

Image devrait ressembler a ca :

![Capture d’écran 2024-03-12 140712](https://github.com/UpGunGame/UpGun-Issues/assets/118850856/bd104f41-12da-480b-a40d-49ddbb196f7d)

**Comment by MaxEstDev** [comment]
C'est mit à jour !
