### ISSUE TITLE
[FR] Petite faute dans la description du jeu 

### ISSUE THREAD

**Issue by ZNS-Dev** [UpGunGame/UpGun-Issues#483]
**Version/Mode de jeu**
2.0.5.1

**Décrivez le bug**
Petite faute 

**Screenshots**
![Screenshot_2024-03-13-17-26-51-984_com valvesoftware android steam community-edit](https://github.com/UpGunGame/UpGun-Issues/assets/118850856/0e37495f-6adb-4156-9930-a978e579067d)

**Comment by MaxEstDev** [comment]
Nickel !
