### ISSUE TITLE
[FR] Item Steam

### ISSUE THREAD

**Issue by ZNS-Dev** [UpGunGame/UpGun-Issues#485]
**Version/Mode de jeu**
2.0.5.1

**Décrivez le bug**
Nom incorrect

**Screenshots**
![image](https://github.com/UpGunGame/UpGun-Issues/assets/118850856/516b450a-1fb8-4e39-a28b-8931211597de)
![image](https://github.com/UpGunGame/UpGun-Issues/assets/118850856/4381ec90-acae-4f91-a76c-d6840255b1cc)

**Comment by MaxEstDev** [comment]
C'est patché !
