### ISSUE TITLE
[FR] Ecran BSOD

### ISSUE THREAD

**Issue by ZNS-Dev** [UpGunGame/UpGun-Issues#488]
**Version/Mode de jeu**
2.0.0.0/Free for All

**Décrivez le bug**
Manque la lettre E du mot Remise (oui j'ai pris le temps de le faire)

**Screenshots**
Avant
![03_BSOD](https://github.com/UpGunGame/UpGun-Issues/assets/118850856/4b5c2695-f70e-4b21-a2ea-1e34d22fafcc)

Après
![03_BSOD](https://github.com/UpGunGame/UpGun-Issues/assets/118850856/f45bac00-0722-4741-af0f-c49790e28ccf)

**Comment by MaxEstDev** [comment]
Merci pour la texture !
C'est corrigé
