### ISSUE TITLE
[FR] Bouton multicolor

### ISSUE THREAD

**Issue by ZNS-Dev** [UpGunGame/UpGun-Issues#490]
**Version/Mode de jeu**
2.0.5.1

**Décrivez le bug**
Le bouton change de couleur quand on ce met dessus

**Video**

https://github.com/UpGunGame/UpGun-Issues/assets/118850856/5ef9e0df-af78-44df-a735-33125aaee547

**Comment by MaxEstDev** [comment]
ah oui wtf

**Comment by MaxEstDev** [comment]
C'était stylé mais c'est corrigé
