### ISSUE TITLE
[FR] Descriptions pas traduits pour toutes les langues (Rage de vivre)

### ISSUE THREAD

**Issue by ZNS-Dev** [UpGunGame/UpGun-Issues#491]
**Version/Mode de jeu**
2.0.5.1

**Screenshots**
![Capture d’écran 2024-03-16 232207](https://github.com/UpGunGame/UpGun-Issues/assets/118850856/55af7381-c670-43ca-bee5-c3f32572ad2e)

**Comment by MaxEstDev** [comment]
C'est bon !
