### ISSUE TITLE
[FR] Logo Balle autoguidé

### ISSUE THREAD

**Issue by ZNS-Dev** [UpGunGame/UpGun-Issues#492]
**Version/Mode de jeu**
2.0.5.1

**Décrivez le bug**
Logo de balle autoguidé pas au bon endroit ou vise null part sans aucun ennemis en face de nous. (En haut a gauche)

**Vidéo**

https://github.com/UpGunGame/UpGun-Issues/assets/118850856/36d6e8b0-8d09-44fc-9f40-e386d46128c0

**Comment by MaxEstDev** [comment]
Je n'ai pas réussis à le reproduire mais j'ai ajouté une sécurité là où je pense que ça foire
