### ISSUE TITLE
[FR] Plateforme Pétrolière

### ISSUE THREAD

**Issue by ZNS-Dev** [UpGunGame/UpGun-Issues#495]
**Version/Mode de jeu**
2.0.5.1

**Décrivez le bug**
Petit trou
![image](https://github.com/UpGunGame/UpGun-Issues/assets/118850856/e7ee914a-1626-4643-b17a-84b5f1ddbfc8)

**Comment by MaxEstDev** [comment]
![image](https://github.com/UpGunGame/UpGun-Issues/assets/96690800/34e35ed0-80b5-4a97-bb97-263850c43f7e)
