### ISSUE TITLE
[FR] Porte dans la map Générateur

### ISSUE THREAD

**Issue by ZNS-Dev** [UpGunGame/UpGun-Issues#498]
**Version/Mode de jeu**
2.0.5.1

**Décrivez le bug**
Porte fermer alors qu'on peut la traverser

**Comportement attendu**
Je pense que du coté host il l'a vois ouverte mais nous en tant que joueur non.

**Screenshots**

https://github.com/UpGunGame/UpGun-Issues/assets/118850856/e6ced986-b78b-475d-93a3-101f0938451a

**Comment by MaxEstDev** [comment]
Merci !
Oui effectivement si un joueur rejoignait après l'ouverture, le comportement n'était pas correct ! C'est corrigé !
