### ISSUE TITLE
[FR] Le skill bullet damage ne s'applique pas correctement

### ISSUE THREAD

**Issue by MaxEstDev** [UpGunGame/UpGun-Issues#5]
Les dégâts de "Bullet.Damage" s'appliquent incorrectement 

**Pour reproduire le bug**
Etapes pour reproduire le bug:
1. Jouer serveur
2. Se give le skill Bullet damage
3. Tirer client 

**Comportement attendu**
Le serveur fait 14 de dégâts
Le client fait 16

**Comment by Zino2201** [comment]
fixé, le MMC des dégâts des balles capturait le mauvais attribute bulletdamage
