### ISSUE TITLE
[FR] Statistiques perdu

### ISSUE THREAD

**Issue by ZNS-Dev** [UpGunGame/UpGun-Issues#500]
**Version/Mode de jeu**
2.0.5.1 beta

**Décrivez le bug**
Si on supprime notre sauvegarde (AppData/Local/UpGun) on perd le stats : Compétences équiées, alors que les autres stats restent comme avant. Beaucoup plus difficle de faire le trophée 100% si on change de PC ou autre.

**Comportement attendu**
Statistique perdu après la suppression de la sauvegarde

**Screenshots**
Avant
![image](https://github.com/UpGunGame/UpGun-Issues/assets/118850856/dd83f005-d977-4ce1-a478-0a81c07a37c8)

Après
![image](https://github.com/UpGunGame/UpGun-Issues/assets/118850856/a213b7bc-ea58-4a0c-807d-be16e2ef2112)

**Comment by MaxEstDev** [comment]
Oué c'est la save, c'est normal
