### ISSUE TITLE
[FR] Faute

### ISSUE THREAD

**Issue by ZNS-Dev** [UpGunGame/UpGun-Issues#505]
**Version/Mode de jeu**
2.0.6.1

**Décrivez le bug**
Petite faute, le S devrais pas ce mettre quand on et tous seul

**Screenshots**
![image](https://github.com/UpGunGame/UpGun-Issues/assets/118850856/8bf6ebe0-6195-402c-8f36-ff1b1b5ddb4a)

**Comment by MaxEstDev** [comment]
pas sûr de corriger ça mdr

**Comment by ZNS-Dev** [comment]
Eh bah zut x)
