### ISSUE TITLE
[FR] Dernière explosion ne fonctionne pas

### ISSUE THREAD

**Issue by Zino2201** [UpGunGame/UpGun-Issues#7]
**Décrivez le bug**
Dernière explosion ne fonctionne pas.

**Pour reproduire le bug**
Prendre dernière explosion

**Comportement attendu**
Explosion à la mort avec dernière explosion.

**Comment by MaxEstDev** [comment]
Elle spawnait à 0,0,0 j'ai utilisé changé la location dans l'ability
